version: 2.1

orbs:
  go: circleci/go@1.7.0
  codecov: codecov/codecov@3.2.0

jobs:
  test:
    parameters:
      go-version:
        type: string
    executor:
      name: go/default
      tag: <<parameters.go-version>>
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          coverprofile: coverage.out
          race: true
          verbose: true
      - when:
          condition:
            and:
              - equal: ["1.17", << parameters.go-version >>]
              - equal: ["master", << pipeline.git.branch >>]
          steps:
            - codecov/upload

workflows:
  tests-matrix:
    jobs:
      - test:
          matrix:
            parameters:
              go-version: ["1.13", "1.14", "1.15", "1.16", "1.17"]
